### ISSUE TITLE
Input value stops updating from signal

### ISSUE THREAD

**Issue by dwarn-axiallon** [silkenweb/silkenweb#11]
Once a text input field has been edited by hand (i.e. type something into the field), the displayed input value will no longer be updated from a read signal. The input value is update just fine before the edit, it is only after the edit that it stops.

Example reproduction:
```rust
fn main() {
    let message = Signal::new("".to_owned());
    let message_read = message.read();
    let message_write = message.write();

    let app = div()
        .child(input().value(message_read))
        .child(button().text("Overwrite Message").on_click(move |_,_| {
            message_write.replace(|_| "Overwrite worked!".to_owned())
        }));

    mount("app", app);
}
```

In the example above, the overwrite button only appears to work if you haven't already typed something into the input.

P.S. I'm a big fan. Of all the rust web frameworks I've tried, this is definitely my favorite. I hope you keep up the great work!

**Comment by simon-bourne** [comment]
Thanks for the kind words about Silkenweb! I think the confusion here is how `<input value="...">` works. If you inspect the DOM, you'll see that updates as you'd expect. It's just that the browser doesn't update what's displayed because the `value` *attribute* just defines the initial value. You need to update the `value` *property* (as opposed to the *attribute*), then the browser will display the updated text. You can do this in Silkenweb with a post render effect:

```rust
use silkenweb::{
    clone,
    elements::{button, div, input},
    mount,
    signal::Signal,
};
use web_sys::HtmlInputElement;

fn main() {
    let message = Signal::new("".to_owned());
    let message_read = message.read();
    let message_write = message.write();

    let app = div()
        .child(
            input()
                .value(&message_read)
                .effect(message_read.map(|message_text| {
                    clone!(message_text);
                    move |elem: &HtmlInputElement| elem.set_value(&message_text)
                })),
        )
        .child(
            button()
                .text("Overwrite Message")
                .on_click(move |_, _| message_write.replace(|_| "Overwrite worked!".to_owned())),
        );

    mount("app", app);
}
```

**Comment by dwarn-axiallon** [comment]
Thank you so much for taking the time to explain. That resolved the issue. The `effect` functionality is elegant and powerful.

Are you looking for contributions? I would be happy to add some documentation to a readme, wiki, or anywhere else regarding the `effect` functionality. If so, just let me know the the best place to put it. Fair warning, I'm not the best when it comes to documentation. :)

This issue can be closed. Thank you again!

**Comment by simon-bourne** [comment]
No problems! The best way to contribute at the moment is to play around with it and log any issues/questions you might have. I've set up a discord server at <https://discord.gg/usSUczZ5ua>.

Be warned that things will change around a bit in the near future, particularly around handling of lists. See the [delta-containers](/silkenweb/silkenweb/tree/delta-containers) branch for the work in progress. I'm going to try and get back to working on that this week.

There are some docs for effects [here](https://github.com/silkenweb/silkenweb/blob/a371accb6698cef8a8b3277d527271f42f8b5502/crates/dom/src/lib.rs#L128-L150). Eventually, I'd like some cookbook style examples, but I think the overall design needs to be a bit more stable first. The TODOMVC example covers most things for now.
