### ISSUE TITLE
Any benchmark comparison 

### ISSUE THREAD

**Issue by vebodev** [silkenweb/silkenweb#26]
I am new to silkenweb, excited with the non-vdom idea.

Are there any simple and quick performance benchmark compared to other rust-wasm frameworks, such as yew, seed, sycamore?

thank you

**Comment by simon-bourne** [comment]
I wrote a harness for js-framework-benchmark in the examples folder. It's a bit of a pain to run as you have to run it within js-framework-benchmark, but [here's the results from a run on my machine](https://github.com/silkenweb/silkenweb/files/8862034/Results.pdf). All the benchmarks were run on an Intel 7700 desktop. The Silkenweb results are from the current head of the git repository, using this build profile:

```toml
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
```
[Results.pdf](https://github.com/silkenweb/silkenweb/files/8862034/Results.pdf)
