### ISSUE TITLE
Code re-organization to improve build times

### ISSUE THREAD

**Issue by akesson** [silkenweb/silkenweb#65]
## Current dependency graph

```mermaid
graph TD;
  silkenweb[<b>silkenweb</b>];
  silkenweb --> base;
  silkenweb --> macros;
  silkenweb --> signals-ext;
  macros --base::css::Source--> base;
  test --base::document--> base;
  test --> silkenweb;
```

## Proposal

1. move `base::document` and `base::window` to the **silkenweb** crate.
2. create a new **styling** crate with all the CSS-related stuff.
3. create a new **styling-macros** crate with CSS-related macros.
4. remove `base` and move its `base::css` code to the **styling** crate.
5. create a new **runtime** crate that contains the runtime (`task::` etc) code.
6. remove the **signals-ext** and move it's code into **runtime**.

```mermaid
graph TD;
  silkenweb[<b>silkenweb</b>];
  styling --> silkenweb;
  styling --> styling-macros;
  silkenweb --> macros;
  silkenweb --> runtime;
  test --> silkenweb;
```

The following is achieved with this:
- the **runtime** crate can be used by business logic so that testing of it can be done without a full **silkenweb** dependency. This guarantees that the business logic doesn't mix in any UI-related things. I.e. the app-state stuff can be added to the **runtime** crate.
- styling is separated into its own crate which depends on and extends **silkenweb**. Like this the styling is optional.

**Let me know what you think. I'll create a PR for it.**

## Note

I'm working on reducing the silkenweb compilation times and the styling (lightningcss, grass, cssparser) is responsible for 40% of it. For my own project, I will use a simple approach of having a parallel css file to each component and at build just appending all these css files into a single main one.

In `my_component.rs`:

```rust
fn my_component<D: Dom>() -> Button<D> {
    button().class("my-component")
}
```
In `my_component.css`:

```css
.my-component {
   component specific standard css
}
```

**Comment by simon-bourne** [comment]
Generally sounds like a great idea. I haven't really given a thought to build times, and should really. A few minor points:

- I'd like to keep `signals-ext` for now. It's meant to be completely independent of the other Silkenweb code.
- My gut feeling is that `styling` and `styling-macros` should be called `css` and `css-macros`, as the purpose is to split out CSS related code to make it optional and improve build times. For example, any future non CSS styling code (whatever that might be) would probably be added to Silkenweb directly so you didn't have to pull in CSS dependencies.

**Comment by akesson** [comment]
Would you like the `css` and `css-macros` extracted from silkenweb and hosted outside in another GitHub repo?

**Comment by simon-bourne** [comment]
No, keep them in the same repo under `packages`.

**Comment by simon-bourne** [comment]
I'm looking at using Features for the CSS part of this:

- Features give us finer grained control, so we don't need `grass` if we don't do Sass, and we don't need `lightningcss` if we don't do transpilation, but we can still do basic Css stuff.
- It's a bit weird to have a public facing `silkenweb-css-macros` crate with a macro that requires you to depend on `silkenweb`.
- We don't end up loads of crates. I want to expose some parts of `css::Source` at some point, which would mean another crate on top of `silkenweb-css` and `silkenweb-css-macros`.

I'm still thinking that `runtime` should be a separate crate.

**Comment by simon-bourne** [comment]
I've merged a change to improve full rebuild times. I've added a `css-transpile` feature, that's not enabled by default. A full build of the `silkenweb` crate has gone from 41.4s before any changes, to 22.5s without `css-transpile` enabled.

It probably won't impact incremental build times, but I haven't tested that. I'll look at extracting a `runtime` crate next.

**Comment by akesson** [comment]
Great news! Thanks!

**Comment by simon-bourne** [comment]
I've added a `silkenweb_task` crate with all the task related items. It's all re-exported in `silkenweb::task`, with some extras (`render_now` and `render_now_sync`). `scope` and `sync_scope` have 2 versions:

- `silkenweb::task::*scope` provide the Task Locals required for rendering, mounting and routing, along with a task queue.
- `silkenweb::task::*scope` with just a task queue.

I think all these changes should give you improved build times when you don't need CSS transpilation, along with the ability to separate business logic from UI presentation code. It doesn't separate the CSS into it's own crate for now, as that's all quite integrated with the rest of Silkenweb.

**Comment by simon-bourne** [comment]
It doesn't affect the public interface, but I've now extracted the CSS stuff from `silkenweb-base` into `silkenweb-css`. It's not meant as a public crate yet, but it's useful for writing proc macros, so I might tidy up the interface and make it public at some point. I'm not planning to split out the macro stuff (that's more entangled with the rest of Silkenweb).
